# Generated by Django 6.0.8 on 2026-09-20 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=240, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('culprit', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(blank=True, max_length=240, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.JSONField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('staging', 'Staging'), ('dev', 'Development')], default='dev', max_length=10)),
                ('level', models.CharField(blank=True, choices=[('error', 'Error'), ('warn', 'Warning'), ('info', 'Info')], max_length=10, null=True)),
                ('metadata', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('recieved_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.issue')),
            ],
        ),
    ]
