# Generated by Django 6.0.8 on 2026-09-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
